#!/usr/bin/env bash
# Displays "Best School" 10 times..
# But for the 9th iteration, displays "Best School" before "Hi".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
