#!/usr/bin/env bash
# Change localhost on host file to resolve @ 127.0.0.2
# Change facebook.com to resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
# cp ~/hosts.new ~/hosts.old

echo "127.0.0.2 localhost" >> hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new

cp hosts.new /etc/hosts
